In [1]:
import numpy as np
import torch

In [15]:
d = np.array([1,2,3])
t = torch.from_numpy(d)
print(f"{d}, {t}")
tensor_memory = t.data_ptr()
array_memory = d.__array_interface__["data"][0]
assert tensor_memory == array_memory #shared underlying memory

[1 2 3], tensor([1, 2, 3])


In [34]:
t = torch.tensor([1,2,3])
t.type, t.shape, t.dtype, t.device

(<function Tensor.type>, torch.Size([3]), torch.int64, device(type='cpu'))

In [3]:
t = torch.tensor([1,2,3], dtype=torch.float64)
t.type, t.shape, t.dtype

(<function Tensor.type>, torch.Size([3]), torch.float64)

In [ ]:
r1 = torch.rand(size=(1,3))
print(r1)

r2 = torch.rand_like(input = r1)
print(r2, r2.dtype)

o1 = torch.ones(size=(1,3))
print(o1, o1.dtype)

o2 = torch.ones_like(r1)
print(o2)

z1 = torch.zeros(size=(1,3))
print(z1, z1.dtype)

ri1 = torch.randint(low=0, high=10, size=(1,3))
print(ri1)

tensor([[0.0050, 0.0118, 0.1677]])
tensor([[0.8116, 0.8795, 0.0562]]) torch.float32
tensor([[1., 1., 1.]]) torch.float32
tensor([[1., 1., 1.]])
tensor([[0., 0., 0.]]) torch.float32
tensor([[5, 3, 4]])


In [41]:
t1 = torch.ones_like(o1)
print(t1.device)

acc_available = torch.accelerator.is_available()
if acc_available:
    acc = torch.accelerator.current_accelerator()
    t2 = t1.to(acc)
    print(t2.device)
    
    #check the memory
    t1_mem = t1.data_ptr()
    t2_mem = t2.data_ptr()
    
    print(t1_mem,' ',t2_mem)

cpu
mps:0
37678662016   37599744832


In [48]:
t1 = torch.rand(size=(2,3,4))
print(t1)

print(t1[0], t1.shape)
print(t1[:,1])
print(t1[...,-1]) #same as t1[:,:,-1]

tensor([[[0.6705, 0.4756, 0.0019, 0.2353],
         [0.0566, 0.5369, 0.0460, 0.7625],
         [0.8698, 0.2390, 0.7598, 0.6562]],

        [[0.6530, 0.5442, 0.0386, 0.5110],
         [0.6259, 0.0911, 0.6555, 0.3758],
         [0.6905, 0.6506, 0.2898, 0.6497]]])
tensor([[0.6705, 0.4756, 0.0019, 0.2353],
        [0.0566, 0.5369, 0.0460, 0.7625],
        [0.8698, 0.2390, 0.7598, 0.6562]]) torch.Size([2, 3, 4])
tensor([[0.0566, 0.5369, 0.0460, 0.7625],
        [0.6259, 0.0911, 0.6555, 0.3758]])
tensor([[0.2353, 0.7625, 0.6562],
        [0.5110, 0.3758, 0.6497]])


In [54]:
t = torch.randint(low=0, high=4, size=(2,3))
print(t)
out = torch.cat([t,t,t], dim=1)
print(out, out.shape)

tensor([[1, 3, 1],
        [3, 3, 2]])
tensor([[1, 3, 1, 1, 3, 1, 1, 3, 1],
        [3, 3, 2, 3, 3, 2, 3, 3, 2]]) torch.Size([2, 9])


In [63]:
t1 = torch.randint(low=0, high=10, size=(3,4))
print(t1 @ t1.T)
print(t1.matmul(t1.T))

tensor([[258, 143, 192],
        [143, 118,  88],
        [192,  88, 192]])
tensor([[258, 143, 192],
        [143, 118,  88],
        [192,  88, 192]])


In [74]:
t1 = torch.randint(low=0, high=10, size=(3,4))
print(t1, t1.sum())
print(t1.sum(dim=0), t1.sum(dim=0, keepdim=True))
print(t1.sum(dim=1), t1.sum(dim=1, keepdim=True))

tensor([[5, 1, 5, 1],
        [8, 5, 2, 9],
        [4, 9, 3, 3]]) tensor(55)
tensor([17, 15, 10, 13]) tensor([[17, 15, 10, 13]])
tensor([12, 24, 19]) tensor([[12],
        [24],
        [19]])


In [79]:
t1 = torch.randint(low=0, high=10, size=(3,4,2))
print(t1, t1.sum())
print(t1.sum(dim=0, keepdim=True).shape, t1.sum(dim=0, keepdim=True).squeeze().shape)
print(t1.sum(dim=1, keepdim=True).shape, t1.sum(dim=1, keepdim=True).squeeze().shape)
print(t1.sum(dim=2, keepdim=True).shape, t1.sum(dim=2, keepdim=True).squeeze().shape)

tensor([[[6, 6],
         [8, 7],
         [9, 9],
         [8, 2]],

        [[7, 1],
         [3, 5],
         [7, 6],
         [7, 6]],

        [[5, 2],
         [8, 7],
         [1, 1],
         [5, 8]]]) tensor(134)
torch.Size([1, 4, 2]) torch.Size([4, 2])
torch.Size([3, 1, 2]) torch.Size([3, 2])
torch.Size([3, 4, 1]) torch.Size([3, 4])
