In [1]:
import torch

In [14]:
x = torch.ones(size=(1,5))
y = torch.zeros(size=(1,3))
w = torch.randn(size=(5,3), requires_grad=True)
b = torch.randn(size=(1,3), requires_grad=True)
z = torch.matmul(x, w) + b
print(f"z.shape={z.shape}")
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print(loss)

z.shape=torch.Size([1, 3])
tensor(2.1355, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [15]:
w.grad, b.grad

(None, None)

In [16]:
loss.backward()
(w.grad, b.grad)

(tensor([[0.0157, 0.3316, 0.2218],
         [0.0157, 0.3316, 0.2218],
         [0.0157, 0.3316, 0.2218],
         [0.0157, 0.3316, 0.2218],
         [0.0157, 0.3316, 0.2218]]),
 tensor([[0.0157, 0.3316, 0.2218]]))

In [27]:
x = torch.ones(size=(1,5))
y = torch.zeros(size=(1,3))
w = torch.randn(size=(5,3), requires_grad=True)
b = torch.randn(size=(1,3), requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

print(f"{b.requires_grad=}, {w.requires_grad=}, {z.requires_grad=}")
with torch.no_grad():
    z = torch.matmul(x, w) + b
    print(f"{b.requires_grad=}, {w.requires_grad=}, {z.requires_grad=}")

b.requires_grad=True, w.requires_grad=True, z.requires_grad=True
b.requires_grad=True, w.requires_grad=True, z.requires_grad=False


In [66]:
x = torch.ones(size=(1,28*28))
y = torch.ones(size=(1,10))

w1 = torch.randn(size=(28*28, 512), requires_grad=True)
b1 = torch.randn(size=(1, 512), requires_grad=True)
l1 = torch.matmul(x, w1) + b1
h1 = torch.nn.ReLU()(l1)

w2 = torch.randn(size=(512, 256), requires_grad=True)
b2 = torch.randn(size=(1, 256), requires_grad=True)
l2 = torch.matmul(h1, w2) + b2
h2 = torch.nn.ReLU()(l2)

w3 = torch.randn(size=(256, 128), requires_grad=True)
b3 = torch.randn(size=(1, 128), requires_grad=True)
l3 = torch.matmul(h2, w3) + b3
h3 = torch.nn.ReLU()(l3)

w4 = torch.randn(size=(128, 10), requires_grad=True)
b4 = torch.randn(size=(1, 10), requires_grad=True)
l4 = torch.matmul(h3, w4) + b4
h4 = torch.nn.ReLU()(l4)

loss = torch.nn.functional.binary_cross_entropy_with_logits(y, h4)

# Clear the previous gradients (it's not going to be there for the first run)
w1.grad = None
b1.grad = None
w2.grad = None
b2.grad = None
w3.grad = None
b3.grad = None
w4.grad = None
b4.grad = None

loss.backward()
print(w2.grad)

tensor([[   0.0000,    0.0000,    0.0000,  ...,    0.0000,    0.0000,
            0.0000],
        [   0.0000,  -11.1565,   -5.8504,  ...,  -18.0604, -101.2931,
            0.0000],
        [   0.0000,  -12.7299,   -6.6754,  ...,  -20.6074, -115.5780,
            0.0000],
        ...,
        [   0.0000,   -2.6552,   -1.3924,  ...,   -4.2984,  -24.1076,
            0.0000],
        [   0.0000,   -0.3611,   -0.1893,  ...,   -0.5845,   -3.2781,
            0.0000],
        [   0.0000,    0.0000,    0.0000,  ...,    0.0000,    0.0000,
            0.0000]])


In [68]:
# Clear the previous gradients
w1.grad = None
b1.grad = None
w2.grad = None
b2.grad = None
w3.grad = None
b3.grad = None
w4.grad = None
b4.grad = None

h2_new = h2.detach()

w3 = torch.randn(size=(256, 128), requires_grad=True)
b3 = torch.randn(size=(1, 128), requires_grad=True)
l3 = torch.matmul(h2_new, w3) + b3
h3 = torch.nn.ReLU()(l3)

w4 = torch.randn(size=(128, 10), requires_grad=True)
b4 = torch.randn(size=(1, 10), requires_grad=True)
l4 = torch.matmul(h3, w4) + b4
h4 = torch.nn.ReLU()(l4)

loss = torch.nn.functional.binary_cross_entropy_with_logits(y, h4)
loss.backward()

print(w2.grad) #we can see that gradient computing is cut off at the h2_new, by treating h2_new as a leaf node.

None
